Add the ability to config HFClient executorService through Gateway to Solve OutOfMemoryError
hyperledger/fabric-gateway-java pull request #124
Opened 2022-11-16 23:59 UTC by mohamedibrahim54

when receiving event block, Channel class call 
`HFClient.getExecutorService.execute(() -> l.listener.received(blockEvent))`

If HFClient executorService is not set, HFClient use the default executorService which is [ThreadPoolExecutor](https://docs.oracle.com/javase/8/docs/api/index.html) with **Direct handoffs strategy** for queuing that strategy hands off tasks to threads without otherwise holding them. it's create new native Thread to run task if if no threads are available to run it.

HFClient default executerServise(ThreadPoolExecutor) has the following properties:
- corePoolSize = 0
- maximumPoolSize = Integer.Max(2147483647)
- keepAliveTime = 60
- timeUnit = SECONDS
- workQueue = SynchronousQueue (that hands off tasks to threads without otherwise holding them. 
		an attempt to queue a task will fail if no threads are immediately available to run it(require unbounded maximumPoolSizes to avoid rejection of new submitted tasks), so a new thread will be constructed)
- threadFactory = create new thread using Executors.defaultThreadFactory()

If the program receives a huge number of block events at the same time,it creates new **native Thread which is expensive resource** for every task to handle block event. this maybe cause 
```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at org.hyperledger.fabric.sdk.Channel.lambda$startEventQue$13(Channel.java:5954)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
depend on machine resouces. 

so we need way to custmize HFClient executerServise through Gateway.Builder, 
The new method:
`Builder clientExecutor(ExecutorService executorService);` 
was added to Gateway.Builder to give the freedom to the library user to use another executerServise with anothor queuing strategies 
like **Unbounded queues Strategy** or Bounded queues strategy to **actually enqueue Tasks**.

### How to use
```
ThreadPoolExecutor executor = new ThreadPoolExecutor(corePoolSize, maximumPoolSize,
				0, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>(),
				r -> {
					Thread thread = defaultThreadFactory().newThread(r);
					thread.setDaemon(true);
					return thread;
				});
Builder builder = Gateway.createBuilder();
builder.identity(wallet, orgMSPName).networkConfig(networkConfigPath).discovery(true)
	.executorService(executor).commitHandler(DefaultCommitHandlers.NONE);
gateway = builder.connect();
```

with the added changes and the executorService above with **Unbounded queues Strategy**, Program was able hadle Tens of thousands of block events received at the same time steadily withot facing annoying OutOfMemoryError and without need to upgrade machines. because **storing tasks in Queue consumes mush less memory than creating native Threads**. in addition to avoid Context Switching.

closes #84 
may also ratated to issue #106

2022-11-21 10:00 UTC, bestbeforetoday commented
Thank you, this change generally looks good, although I would really like to see some accompanying unit tests to ensure behaviour is not accidentally broken by any future code changes.

I also have a few questions / discussion points:

1. Would just changing the maximum thread pool size using the **org.hyperledger.fabric.sdk.client.thread_executor_maximumpoolsize** system property (or **ORG_HYPERLEDGER_FABRIC_SDK_CLIENT_THREAD_EXECUTOR_MAXIMUMPOOLSIZE** environment variable) be sufficient to solve the problem?
2. If the queue should also be unbounded for good behaviour when the maximum thread pool size is limited, would it make sense to change the default implementation in fabric-sdk-java to use an unbounded queue?
3. If the flexibility if configuring a specific executor service is really necessary, would it be preferrable to expose the `HFClient getClient()` method that exists on GatewayImpl in the Gateway interface for application use?

All of these options would still require your change to the `GatewayImpl(GatewayImpl)` copy constructor.

What do you think? Also @andrew-coleman?

2022-11-21 22:57 UTC, mohamedibrahim54 commented
Hi, I am pleased to answer these questions and have discussion.

> 1. Would just changing the maximum thread pool size using the org.hyperledger.fabric.sdk.client.thread_executor_maximumpoolsize system property (or ORG_HYPERLEDGER_FABRIC_SDK_CLIENT_THREAD_EXECUTOR_MAXIMUMPOOLSIZE environment variable) be sufficient to solve the problem?

I've tried this solution before and got what I expected according to the [ThreadPoolExecutor](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html) documentation:

> an attempt to queue a task will fail if no threads are immediately available to run it, so a new thread will be constructed. This policy avoids lockups when handling sets of requests that might have internal dependencies. **Direct handoffs generally require unbounded maximumPoolSizes to avoid rejection of new submitted tasks**. This in turn admits the possibility of unbounded thread growth when commands continue to arrive on average faster than they can be processed.


When program receives a huge number of block events at the same time, the RejectedExecutionException exception is Thrown as following:

```
java.util.concurrent.RejectedExecutionException: Task org.hyperledger.fabric.sdk.Channel$$Lambda$3475/1749425461@521db6f2 rejected from java.util.concurrent.ThreadPoolExecutor@40f87470[Running, pool size = 32, active threads = 32, queued tasks = 0, completed tasks = 35]
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at org.hyperledger.fabric.sdk.Channel.lambda$startEventQue$13(Channel.java:5954)
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dev-eir-prod-app-0.3.0-SNAPSHOT  | 	at java.lang.Thread.run(Thread.java:748)
```

So this did not solve the problem because for example if program recieves 33 block events at the same time and maximumPoolSize = 32, This means losing the last event.

> 2. If the queue should also be unbounded for good behaviour when the maximum thread pool size is limited, would it make sense to change the default implementation in fabric-sdk-java to use an unbounded queue?

Yes, I think **it would be great to change the default implementation to use an unbounded queue. as native Thread is expensive from the point of view of memory, A large block of memory has to be allocated and initialized for the thread stack and thread creation process is consuming processor time in addition to "more Threads means more context switching" which has a bad effect on performance.**

> 3. If the flexibility if configuring a specific executor service is really necessary, would it be preferrable to expose the HFClient getClient() method that exists on GatewayImpl in the Gateway interface for application use?

Actually, expose `client()` method that exists on `GatewayImpl.Builder` is the first thing I did. but I recognize that **add BlockListener creates new ListenerSession which creates new Gateway Which in turn creates new HFClient with the default ExecutorService.** 
The reason is that when invoke
https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/main/java/org/hyperledger/fabric/gateway/impl/NetworkImpl.java#L102
or
https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/main/java/org/hyperledger/fabric/gateway/impl/NetworkImpl.java#L125
It creates new ReplayListenerSession
https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/main/java/org/hyperledger/fabric/gateway/impl/event/ReplayListenerSession.java#L31
Which **creates new gateway and new NetworkImpl Object.** 
in GatewayImpl constructor `GatewayImpl(GatewayImpl)` it creates new Gateway from old Gateway object. the problem is acually here:
https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/main/java/org/hyperledger/fabric/gateway/impl/GatewayImpl.java#L207
It creates new client with the default ExecutorService and don't use the client set via GatewayImpl.Builder.

So now it's look fine. **why you don't use getClient() method that exists on GatewayImpl in the Gateway interface after expose it?** 
The reason is when NetworkImpl is created, it 's initialize Channel (Network object have one Channel object) and this invoke 
https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/main/java/org/hyperledger/fabric/gateway/impl/NetworkImpl.java#L59
which in turn invoke startEventQue to start Transaction monitoring and it's acually use HFClient ExecutorService:
https://github.com/hyperledger/fabric-sdk-java/blob/1d632fc6503a48a2f166a4a3540709019f08b4ef/src/main/java/org/hyperledger/fabric/sdk/Channel.java#L5904
The `getExecutorService()` method creates the Default Executor Service if Executor Service == null (which always true, If it is not set before create new Network object). After this point, you can't set ExecutorService. and if you try to getClient() and setExecutorService, you gets InvalidArgumentException:
https://github.com/hyperledger/fabric-sdk-java/blob/1d632fc6503a48a2f166a4a3540709019f08b4ef/src/main/java/org/hyperledger/fabric/sdk/HFClient.java#L138
and this make sense maybe to avoid losing events in the previous Executor. 
**Rule of thumb: After create Network object you can't set HFClient ExecutorService.**

> All of these options would still require your change to the GatewayImpl(GatewayImpl) copy constructor.

yes, As already explained.

**Finally, I think I only need to config client ExecutorService currently. Although I know that ExecutorService will be shared between all Gateway Clients for now. and I think it would be great to change the default implementation to use an unbounded queue.**

2022-11-23 13:21 UTC, bestbeforetoday commented
How about this approach?

1. Make the following (hopefully) sensible changes to fabric-sdk-java, so things work better out-of-the-box:
    - Change the default executor service to:
       ```java
      new ThreadPoolExecutor(
          CLIENT_THREAD_EXECUTOR_COREPOOLSIZE,
          CLIENT_THREAD_EXECUTOR_MAXIMUMPOOLSIZE,
          CLIENT_THREAD_EXECUTOR_KEEPALIVETIME,
          CLIENT_THREAD_EXECUTOR_KEEPALIVETIMEUNIT,
          new LinkedBlockingQueue<>(),
          r -> {
              Thread t = threadFactory.newThread(r);
              t.setDaemon(true);
              return t;
          }
      );
      ```
    - Change the default `CLIENT_THREAD_EXECUTOR_MAXIMUMPOOLSIZE` to a smaller value than `Integer.MAX_VALUE`. Maybe `Runtime.getRuntime().availableProcessors() + 1`? Better suggestions welcome!
    - Make the `HFClient.getExecutorService()` method public.
2. Make the following changes to fabric-gateway-java:
    - Change the Gateway copy constructor (used when creating an event replay session) to get the executor from the previous HFClient (and set it on the new Gateway instance's HFClient:
        ```java
        client.setExecutorService(that.client.getExecutorService());
        ```
    - Add `HFClient getClient()` to the Gateway interface.

I _think_ this should make it work out-of-the-box for you. If not optimally, then at least without any failures. Some additional tweaking of the thread pool for your scenario could be done by only changing the configuration properties. And then for cases where you really need your own thread pool implementation, you have the option of diving down to the fabric-sdk-java API, but keeping those implementation details out of the higher-level fabric-gateway-java API.

What do you think?

2022-11-26 20:42 UTC, mohamedibrahim54 commented
This approach that you suggested is also convenient. I have implemented these changes(suggested changes + make `HFClient`'s `getExecutorService()` method public) and tested them using the Application, it also works without any failures.


Finally, I hope that my experience in solving this problem will be useful to other and save them the effort and time of investigation and solution.

Thanks

2022-11-29 18:49 UTC, bestbeforetoday commented
I have published a [v2.2.19](https://github.com/hyperledger/fabric-sdk-java/releases/tag/v2.2.19) release of fabric-sdk-java that includes the changes described above so this PR now builds. Please could you make an update to the fabric-sdk-java dependency in **pom.xml** as part of this PR to ensure the minimum required version of fabric-sdk-java is resolved:

```xml
<dependency>
    <groupId>org.hyperledger.fabric-sdk-java</groupId>
    <artifactId>fabric-sdk-java</artifactId>
    <version>[2.2.19,2.3.0)</version>
</dependency>
```

2022-11-30 09:34 UTC, bestbeforetoday requested changes
In addition to the dependency update to require fabric-sdk-java version 2.2.19 or later, this also needs a unit test to ensure the new behaviour is not accidentally broken by any future changes. Look at this one as an example:

https://github.com/hyperledger/fabric-gateway-java/blob/37602a7a6444bf93d8ef620250f69960e3a9dbe7/src/test/java/org/hyperledger/fabric/gateway/impl/GatewayTest.java#L102-L109

2022-12-01 07:34 UTC, bestbeforetoday approved these changes

2022-12-01 07:37 UTC, merged

2022-12-01 07:38 UTC, bestbeforetoday commented
Thank you for your investigation of this issue and for contributing a fix!

2022-12-01 15:01 UTC, bestbeforetoday commented
@Mergifyio backport release-2.2